spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: testuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 400
        use_sql_comments: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

